version: '2.10'

services:
  db:
    image: postgres:13.2-alpine
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: salasana
    volumes:
      - type: bind
        source: ./database
        target: /var/lib/postgresql/data
    container_name: teht_2.10_db

  frontend:
    image: frontend_ex210

    environment:
      - REACT_APP_BACKEND_URL=http://localhost/api
    container_name: teht_2.10_frontend

  backend:
    image: backend_ex29
    environment:
      - REQUEST_ORIGIN=http://localhost
      - REDIS_HOST=redis
      - POSTGRES_HOST=db
      - POSTGRES_DATABASE=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=salasana
    container_name: teht_2.10_backend

  redis:
    image: redis:latest
    container_name: teht_2.10_redis

  nginx:
    image: nginx
    ports:
      - 80:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    container_name: teht_2.10_nginx

volumes:
  database:
