name: Release DevOps with Docker 

# On a push to the main
on:
  push:
    branches:
      - main

jobs:
  publish-docker-hub:
    name: Publish image to Docker Hub
    runs-on: ubuntu-latest
    steps:
    # Checkout to the repository
    - uses: actions/checkout@v2
.
    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    # Builds expressapp image
    - name: Build and push
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: vulpecula78/expressapp:latest
