version: '2.8'

services:
  db:
    image: postgres:13.2-alpine
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: salasana
    volumes:
      - type: bind
        source: ./database
        target: /var/lib/postgresql/data
    container_name: teht_2.8_db

  frontend:
    image: frontti
    ports:
      - 5000:5000
    environment:
      - REACT_APP_BACKEND_URL=http://localhost:8080
    container_name: teht_2.8_frontend

  backend:
    image: backend
    ports:
      - 8080:8080
    environment:
      - REQUEST_ORIGIN=http://localhost:5000
      - REDIS_HOST=redis
      - POSTGRES_HOST=db
      - POSTGRES_DATABASE=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=salasana
    container_name: teht_2.8_backend

  redis:
    image: redis:latest
    container_name: teht_2.8_redis

  nginx:
    image: nginx
    ports:
      - 80:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    container_name: teht_2.8_nginx

volumes:
  database:
